### PR TITLE
Update docs with email config

### PR DESCRIPTION
**Pull request by naglepuff**
Add some basic instructions as well as screenshots to aid in enabling emails from girder.

### CODE REVIEW

**Comment by manthey** [comment]
This looks good.  Do you know when Registration is set to "Admin approval required" if the admin user gets an email when someone tries to register?

**Comment by naglepuff** [comment]
> This looks good. Do you know when Registration is set to "Admin approval required" if the admin user gets an email when someone tries to register?

Yes. An email is sent to all "admin" users in the system. From that email they can follow a link to the new user's account, and from there they can approve the new user from the "Actions" menu.

**Comment by manthey** [comment]
After consideration, I think this needs to be in the installation document rather than the usage document, as the typical user won't need to do this.

**Comment by naglepuff** [comment]
> After consideration, I think this needs to be in the installation document rather than the usage document, as the typical user won't need to do this.

I think that makes sense. See 54028e1. I've added the information right below the "Admin user" section, since that felt like the section in the docs with the strongest relationship to email. If you think there's another place that is more appropriate, let me know.

**Review by manthey — APPROVED** [review]

**Comment by manthey** [comment]
Closes #209.

**Pull request merged**
