### PR TITLE
Add ability to run OCR on imported images

### PR DESCRIPTION
**Pull request by naglepuff**
This PR pertains to #204 
This PR adds functionality to run optical character recognition on imported images in the WSI DeID plugin. There are three ways a user can trigger this process.

1. During import
2. From the `AvailableToProcess` folder
3. On a single image in the `AvailableToProcess` folder

For (1), there is a new plugin setting to enable starting OCR during an import. To enable, navigate to `Admin console` > `Plugins` > `WSI DeID` and ensure that `Find Label Text on Import` is checked. For (2), there is a new action button next to `Import` that will trigger OCR. For (3), there is a workflow button on the item view.

All three methods will run OCR asynchronously as a local girder job. The job can be monitored from the jobs page. Any text found in the label image of a WSI is added to the item metadata for the girder item.

### CODE REVIEW

**Comment by manthey** [comment]
The current performance is fine, unless a bit of tuning would result in nearly the same quality but significant speed improvements.

Ultimately, on import, we'll end up have an import excel/csv file that has some text fields in it and IF we can unique match the OCR text to a single line in the import file, then we'll use another field from that line as the name of the file.

**Comment by naglepuff** [comment]
> Ultimately, on import, we'll end up have an import excel/csv file that has some text fields in it and IF we can unique match the OCR text to a single line in the import file, then we'll use another field from that line as the name of the file.

What will this look like exactly? Will a target column in the import file be configurable, and we'll check OCR results against the specified column to try and match an image to a row? Should that be a plugin setting or a deployment setting? 

Should the OCR results still be added to the metadata?

**Comment by manthey** [comment]
I think this looks like having a different schema file (replacing or extending the schema in wsi_deid/schema/importManifestSchema.json by mounting a different schema in the docker for instance) where `InputFileName` is not defined.  The image would first be placed in a new folder, defining one additional folder for the project -- so a folder that would be called some thing ("Unfiled"?).  When OCR results are finished (I'd still add them to the metadata), we would check if there are words in the OCR that uniquely match some fields in a single row of the latest upload file (so we'll need to store that somewhere, possibly with the OCR job).  If these match, the file would then be given a name from the upload file (e.g., from the `ImageID` field or another configurable base field (e.g, `TokenID`) which would then be suffixed with a unique value).  Once renamed, the file would be moved into the AvailbleToProcess folder and be processed as before.

**Comment by manthey** [comment]
I've transferred some of this commentary about how this will be used into issue #205 which is now the road map for the rest of this work.  If you think the OCR is working adequately, we could review and merge this and proceed with the other parts of the work.  This will probably be brittle, but that is acceptable for now.

**Comment by naglepuff** [comment]
> I've transferred some of this commentary about how this will be used into issue #205 which is now the road map for the rest of this work. If you think the OCR is working adequately, we could review and merge this and proceed with the other parts of the work. This will probably be brittle, but that is acceptable for now.

Sure, I'll mark this as ready for review, and look over #205 to see what's next.

**Review by manthey — APPROVED** [review]
Let's merge this as it is.  I'll create an issue or two with some follow up work with can be lower priority than the other tasks.

**Pull request merged**
